# Generated by Django 5.2.7 on 2025-11-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_block_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Superuser'), ('staff', 'Staff'), ('active', 'Active User')], max_length=20)),
            ],
        ),
    ]
