# Generated by Django 5.2.7 on 2025-11-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_display_name_profile_display_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('professional', 'Professional'), ('admin', 'Admin')], default='basic', max_length=20),
        ),
    ]
