# Generated by Django 5.2.7 on 2025-11-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='analytics_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Basic', max_length=20),
        ),
    ]
