# Generated by Django 5.2.7 on 2025-11-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_analytics_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Professional', 'Professional'), ('Admin', 'Admin')], default='basic', max_length=20),
        ),
    ]
